apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-auto-sync-self-heal-disabled
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-argoapp
    repoURL: https://github.com/mayzhang2000/argocd-example-apps.git
  syncPolicy:
    automated: {}
