# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  stage: dev
resources:
  - job.yaml
  - deployment.yaml
patchesJson6902:
  - path: patches/job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: app-job-test