apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: freight-posting-test
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: freight-posting-test
    helm.sh/chart: node-4
  name: freight-posting-test
spec:
  replicas: 8
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/instance: freight-posting-test
      app.kubernetes.io/name: freight-posting-test
  template:
    metadata:
      labels:
        app: freight-posting-test
        app.kubernetes.io/component: service
        app.kubernetes.io/instance: freight-posting-test
        app.kubernetes.io/name: freight-posting-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/role
                    operator: In
                    values:
                      - application
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - freight-posting-test
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 1
      containers:
        - env:
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: license
                  name: newrelic-config
            - name: NEW_RELIC_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: newrelic-config
            - name: NEW_RELIC_ENABLED
              valueFrom:
                secretKeyRef:
                  key: enabled
                  name: newrelic-config
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ANALYTICS_BASE_URL
              value: 'https://analytics.api.xxxx'
            - name: API_KEY
              value: xxxxx
            - name: APP_ID
              value: Posting-Service
            - name: CSB_KAFKA_BROKERS
              value: >-
                xxxx
            - name: CSB_KAFKA_CONSUMER_ENABLED
              value: 'true'
            - name: CSB_KAFKA_INCOMING_SYNC_TOPIC
              value: fmcSync.asset
            - name: CSB_KAFKA_OUTGOING_SYNC_BROKERS
              value: >-
                xxxx
            - name: CSB_KAFKA_OUTGOING_SYNC_NUM_PARTITIONS
              value: '30'
            - name: CSB_KAFKA_OUTGOING_SYNC_TOPIC
              value: stream.posting-sync
            - name: CSB_KAFKA_PRODUCER_ENABLED
              value: 'true'
            - name: CSB_PROXY_USER_LOGINID
              value: postingSrvcPrxy
            - name: CSB_PROXY_USER_PASSWORD
              value: c5395cada3cc
            - name: CSB_SOAP_URL
              value: 'http://csbqaq'
            - name: IS_OFFLINE
              value: 'false'
            - name: LOAD_POSTING_COLLECTION
              value: loadPostings
            - name: LOGGER_LEVEL
              value: info
            - name: MONITORING
              value: NEW_RELIC
            - name: NETWORK_BASE_URL
              value: 'https://network.api.xxxx'
            - name: NEW_RELIC_APP_NAME
              value: Freight Posting Service
            - name: OAUTH2_AUDIENCE
              value: 'https://test-api.xxx'
            - name: OAUTH2_CLIENT_ID
              value: xxxx
            - name: OAUTH2_CLIENT_SECRET
              value: xxxxx
            - name: OAUTH2_ISSUER
              value: 'https://login.test.xxxx/'
            - name: PORT
              value: '3000'
            - name: POSTING_DB_NAME
              value: freight-posting
            - name: POSTING_DB_URL
              value: >-
                mongodb://master:xxx@xxxxx.us-west-2.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
            - name: SEQUENCE_BATCH_SIZE
              value: '30'
            - name: SEQUENCE_COUNTER_COLLECTION
              value: sequenceCounters
            - name: SEQUENCE_COUNTER_DB
              value: sequences
            - name: SEQUENCE_DB_URL
              value: >-
                mongodb://master:xxxx@xxxx.us-west-2.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=primary&retryWrites=false
            - name: SEQUENCE_WRITE_CONCERN
              value: '1'
          image: 'xxxxx'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: node
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 3000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      hostAliases:
        - hostnames:
            - pdxcsbqa1-01
          ip: 10.6.11.11
        - hostnames:
            - pdxcsbqa1-02
          ip: 10.6.11.12
        - hostnames:
            - pdxcsbqa1-03
          ip: 10.6.11.13
      securityContext:
        runAsGroup: 5000
        runAsUser: 5000
      serviceAccountName: freight-posting-test